download:
    git clone https://github.com/lexibank/lexibank-analysed --branch v1.0 cldf-data/lexibank-analysed
	git clone https://github.com/concepticon/concepticon-data --branch v3.1.0 cldf-data/concepticon-data
    git clone https://github.com/intercontinental-dictionary-series/idssegmented cldf-data/idssegmented
	git clone https://github.com/lexibank/seifartecheverriboran cldf-data/seifartecheverriboran
