wordlist:
	edictor wordlist --name=npl_data --data=../cldf/cldf-metadata.json --preprocessing=preprocessing.py --addon="language_subgroup:subgroup","alignment:alignment","cognacy:cogid","partial_cognacy:cogids","source:source"

msa:
	edictor wordlist --name=npl_msaligned --data=../cldf/cldf-metadata.json --preprocessing=realign.py --addon="language_subgroup:subgroup","alignment:alignment","cognacy:cogid","partial_cognacy:cogids","source:source"