wordlist:
	edictor wordlist --name=d_northperulex --data=../cldf/cldf-metadata.json --addon="language_family:family","cognacy:cogid","partial_cognacy:cogids","morphemes:morphemes","borrowing:borrowing","comment:note"

map:
	Rscript map.R
