wordlist:
	edictor wordlist --name=d_northperulex --data=../cldf/cldf-metadata.json --preprocessing=s_realign.py --addon="language_subgroup:subgroup","cognacy:cogid","partial_cognacy:cogids","morphemes:morphemes","borrowing:borrowing","comment:note"

map:
	Rscript map.R
